[package]
name = "hex2b64"
version = "0.1.0"
edition = "2021"
author = ["supinie"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
