[package]
name = "frequency_analysis"
version = "0.1.0"
edition = "2021"
authors = ["supinie"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecount = "0.6.8"
crypto_library = { version = "0.1.0", path = "../crypto_library" }
